### ISSUE TITLE
need help with 0 bytes

### ISSUE THREAD

**Issue by Cisar1235** [chenxinfeng4/ffmpegcv#43] opened 2024-03-31 19:50 UTC
Hi, first of all thank you for this wonderful solution. I am trying to convert my exising cv2 writer to ffmpegcv but video is always 0 bytes no matter how i tried. Can you please point out what I did wrong? Thank you in advance. I understand the image width height can be automated but I just wanna stick to current setup for future changes. CV2 ran without problem.

           
            frame = cv2.imread(os.path.join(image_folder, images[0]))
            height, width, layers = frame.shape
            #video = cv2.VideoWriter(video_name, fourcc, 15, (width, height))
            video = ffmpegcv.VideoWriterNV(video_name, 'hevc_nvenc', 15, (width, height)) #40 
            for image in images:
                img = cv2.imread(os.path.join(image_folder, image))
                video.write(img)            
            video.release()

**Comment by chenxinfeng4** [comment] 2024-04-01 01:23
Did you try `VideoWriter` instead of `VideoWriterNV`? 

```python
video = ffmpegcv.VideoWriter(video_name, None, 15) 
video = ffmpegcv.VideoWriterNV(video_name, None', 15) 
video = ffmpegcv.VideoWriterNV(video_name, 'hevc_nvenc', 15, (width, height)) 
```

You may have a error version of ffmpeg.

**Comment by chenxinfeng4** [comment] 2024-04-01 02:54
Firstly, you can check whether `VideoWriter` works for you.
Secondly, you can try `ffmpeg -i EXAMPLE.mp4 -c:v hevc_nvenc out.mp4` to check the ffmpeg GPU encoder.
Report these results to me.

**Comment by chenxinfeng4** [comment] 2024-04-01 13:51
I see. Can you update the ffmpegcv to the latest version? 
> pip install git+https://github.com/chenxinfeng4/ffmpegcv

Currently, there is no easy way to debug the ffmpegcv. I'll create a specific debuger this week.

**Comment by chenxinfeng4** [comment] 2024-04-01 17:01
i updated  the ffmpegcv. It will show your  error message.

pip install -U git+xxxxxxx

**Comment by chenxinfeng4** [comment] 2024-04-02 01:37
Whether this demo code works for you?
```python
# try a simple code
import ffmpegcv
import numpy as np

vout = ffmpegcv.VideoWriter('a.mp4', None, fps=20)
frame = np.random.randint(0, 256, size=(480, 640, 3), dtype=np.uint8)
frame[100:200, 100:300, :] = 0

for _ in range(100):
    vout.write(frame)
vout.release()
```

```bash
# bash
$ ffprobe  a.mp4
```

**Comment by chenxinfeng4** [comment] 2024-04-02 03:21
The `VideoWriter` is a CPU version, which should works without gpu and cross platforms. I guess you have a wrong ffmpeg installation. What's your platform, windows or linux, x86 or arm?

**Comment by chenxinfeng4** [comment] 2024-04-02 04:12
1. Where did you download the ffmpeg, give me the link, I would check it.
2. May be you can change the codec if something wrong with ffmpeg.
```python
import ffmpegcv
import numpy as np
codec = ['mjpeg', 'mpeg4', 'libx264']
vout = ffmpegcv.VideoWriter('a.mp4', codec='mjpeg', fps=20) #try different codecs
frame = np.random.randint(0, 256, size=(480, 640, 3), dtype=np.uint8)
frame[100:200, 100:300, :] = 0

for _ in range(100):
    vout.write(frame)
vout.release()
```

**Comment by chenxinfeng4** [comment] 2024-04-03 12:37
I found the bug. The bug is only for windows. The `vid.release()` will try to terminate the writer process. However, the principle of windows process is totally different with linux. So, the `vid.release()` fails to release the file.

WTF windows.

 ```python
# fail in windows system
def release_process(process):
    if hasattr(process, "stdin"):
        process.stdin.close()
    if hasattr(process, "stdout"):
        process.stdout.close()
    if hasattr(process, "terminate"):
        process.terminate()
    if hasattr(process, "wait"):
        process.wait()
```

I will fix this bug in a week.

**Comment by chenxinfeng4** [comment] 2024-04-04 16:12
I've fixed the bug, please check the latest version by 
>pip install -U git+https://github.com/chenxinfeng4/ffmpegcv

So, the vid.release() is fixed as below:
```
def release_process(process:Popen):
    if hasattr(process, "stdin"):
        process.stdin.close()
    if hasattr(process, "stdout"):
        process.stdout.close()
    if hasattr(process, "terminate") and not _is_windows:
        process.terminate()
    if hasattr(process, "wait"):
        process.wait()
```

There would be other bugs in windows. Feel free to report issues.

**Comment by chenxinfeng4** [comment] 2024-04-04 16:25
did you test on my demo  code? the latest version of ffmpegcv only modify the 'release' and won't affect 'write' function.

**Comment by chenxinfeng4** [comment] 2024-04-04 16:37
I'll test on another windows  PC next day

**Comment by chenxinfeng4** [comment] 2024-04-05 05:02
> ffmpeg_writer.py", line 84, in write self.process.stdin.write(img) BrokenPipeError: [Errno 32] Broken pipe
> https://www.gyan.dev/ffmpeg/builds/ found at https://ffmpeg.org/download.html

No problem on anther PC, latest ffmpeg build. I encounter the BrokenPipeError only when I didn't close the video file. Please close the video file, or create a new one.

```python
import ffmpegcv
import numpy as np

vout = ffmpegcv.VideoWriter('a2_x264.mp4', codec='libx264', fps=20) #try different codecs
frame = np.random.randint(0, 256, size=(480, 640, 3), dtype=np.uint8)
frame[100:200, 100:300, :] = 0

for _ in range(200): vout.write(frame+np.random.randint(0, 50, size=(480, 640, 3), dtype=np.uint8))
vout.release()
```

**Comment by ajtao** [comment] 2024-09-19 22:15
Hi @chenxinfeng4. First off thank you for the amazing library, its very useful!

I have noticed that from 0.3.11 to 0.3.13, ffmpegcv no longer will exit cleanly with Ctrl-C. This is unfortunate, because it was extremely useful that ffmpegcv could generate valid video files when the program is stopped with Ctrl-C.  I've got a whole codebase built around streaming videos with ffmpegcv's help and they run for many minutes or hours, so being able to Ctrl-C cleanly is a very positive feature.

A simple repro of what i'm talking about is below. Save it as "test.py" and run "python test.py <some video file>".
If you Ctrl-C this program with 0.3.11, it will exit cleanly and "out.mp4" will be a valid video file. However if you're using 0.3.13 or later, it'll raise a BrokenPipeError and the written video file will be invalid.

`
import ffmpegcv
import argparse

from tqdm import tqdm

parser = argparse.ArgumentParser("test")
parser.add_argument('vid', type=str, help='input video')
args = parser.parse_args()

vid_rd = ffmpegcv.VideoCapture(args.vid)
vid_wr_fn = 'out.mp4'
vid_wr = ffmpegcv.VideoWriter(vid_wr_fn, codec='hevc', fps=vid_rd.fps)

for frame in tqdm(vid_rd, total=len(vid_rd), desc='read video'):
    vid_wr.write(frame)
`

**Comment by chenxinfeng4** [comment] 2024-09-20 01:29
Thanks for your comment. The test code is clear, I'll check it in a week.

**Comment by chenxinfeng4** [comment] 2024-09-20 10:33
@ajtao I found the bug. It's caused by how python releases a subprocess. It behaves differently.

In the old version, friendly for ctrl+c
```python
# create the video writer Popen
def run_async(args):
    quiet = True
    stderr_stream = subprocess.DEVNULL if quiet else None
    bufsize = -1
    return Popen(
        args,
        stdin=PIPE,
        stdout=PIPE,
        stderr=stderr_stream,
        shell=True,
        bufsize=bufsize,
    )
```
Where the `args` should be originally somthing like this
```
 ffmpeg -y -loglevel warning -f rawvideo -pix_fmt bgr24 -s 640x360 -r 24.0 -i pipe: -r 24.0
 -c:v h264 -pix_fmt yuv420p "/home/out.mp4"
```
It's not secure for `shell=True` because INJECTION RISK. So I changed it to by `shlex.split` and `shell=False`.

In the latest version 3.13 or later. The Popen use `shell=False`.
```python
# version latest
def run_async(args):
    quiet = True
    stderr_stream = subprocess.DEVNULL if quiet else None
    bufsize = -1
    if isinstance(args, str):
        args = shlex.split(args)
    return Popen(
        args,
        stdin=PIPE,
        stdout=PIPE,
        stderr=stderr_stream,
        shell=False,
        bufsize=bufsize,
    )
```

```python
args  = ['ffmpeg', '-y',  '-loglevel', 'warning', '-f', 'rawvideo',  '-pix_fmt',  'bgr24',
 '-s',  '640x360', '-r', '24.0', '-i', 'pipe:', '-r', '24.0', '-c:v', 'h264', '-pix_fmt',
 'yuv420p',  '"/home/out.mp4"']
```

However, it cause the differenct behaviors while releasing, even them used the same release function. Finally, caused the unexpected ctrl+c problem.
```python
def release_process(process):
     process.stdin.close()
     process.stdout.close()
     process.terminate()
     process.wait()
```

I try to handle the release function, but that's challenge.

**Comment by chenxinfeng4** [comment] 2024-09-20 11:49
@ajtao try the latest version to see whether the update works for you.
```
pip install git+https://github.com/chenxinfeng4/ffmpegcv
```

**Comment by ajtao** [comment] 2024-09-20 14:07
Thank you @chenxinfeng4 ! I just tried 0.3.15c, but still getting the broken pipe error.

**Comment by chenxinfeng4** [comment] 2024-09-20 14:11
The broken pipe is not a actual error. It's you closing the file by exception (ctrl c). Check the output video file.



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/20/2024 22:08 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [chenxinfeng4/ffmpegcv] need help with 0 bytes (Issue #43) |

Thank you @chenxinfeng4 ! I just tried 0.3.15c, but still getting the broken pipe error.

**Comment by ajtao** [comment] 2024-09-20 14:22
Ah ok, you're right, it works now!

**Closed** 2024-09-21 07:53 UTC
